### ISSUE TITLE
Concepts Feedback

### ISSUE THREAD

**Issue by brandonbrown** [fs-tech-degs/capstone-DVBrown93#1]
> This is a copy of my message from Discord for archiving and open-discussion

The first idea is being seen as a little too soft. This would be a good self-research project, but not fitting for the expectations of this class or a real product. We're going to recommend more time spent in the 2nd idea.

However, there's a lot of potential in the 2nd idea but we're going to need to flush that out. 

Consider this: What problems do children have around book discovery. As adults we solve this with book clubs and recommendations. Would it be teachers recommending books to kids currently? Can that experience be improved upon or what pain points are around that?

It was also requested that as part of your final tech stack decision, you explain why you would like to use mongo vs a relational database solution.

**Comment by DVBrown93** [comment]
> These are notes from the concept feedback discussion

Rework it to be for children first, give some type of gratification by looking into gamification
Design pattern for children
psychology/behavior change
psychology of habit-forming of children (medium articles)
Possibly look for API to test/quiz generator to quiz the user

Possible read hooked and reality is broken to continue to get a better understanding of gamification

Recommended looking at children learning app or apps that are using gamification like Duolingo 

> Question Response
**Why you would like to use mongo vs a relational database solution?**

There are a few reasons I want to use mongo over a relational database. I did consider a relational database over a non-relational. However, one of the reasons I went with non-relational is because of the flexibility of Mongo. Considering we are just starting the amount of data isn't substantial enough to warrant a relational database. All of the types of data that will be stored nor the relationship are fully known only some and with Mongo, it allows the flexibility to make changes and relationship. The amount of time querying for the data in Mongo is faster than in a relational database such as MySQL because the data is in all one document and not multiple tables. Mongo with Mongoose adds another layer or validation, therefore there's database validation, serverside validation, and client-side validation.  The transition to mobile is easier because Mongo gives the ability to use the same database with mobile where with a relational database there may be some restructuring needed meaning a second database. Lastly, after some discussion, we are considering some gamification aspects to the application and during my research, SEGA has found and switched to using mongo to improve the gaming experience. 

[https://www.mongodb.com/blog/post/sega-hardlight-migrates-to-mongodb-atlas-simplify-ops-improve-experience-mobile-gamers](url)
